# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_auto_20170525_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
